In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("deliveries.csv")
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [ ]:
# checking the info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [ ]:
# checking the unique values in Extras_type and filling the null values with "Normal"
df['extras_type'].unique()
df['extras_type']=df['extras_type'].fillna("Normal")

In [ ]:
# checking the unique values in player_dismissed and filling the null values with "Not Dismissed"
print(df['player_dismissed'].unique())
df['player_dismissed']=df['player_dismissed'].fillna("Not Dismissed")

# checking the unique values in fielder and filling the null values with "No Fielder"
print(df['fielder'].unique())
df['fielder']=df['fielder'].fillna("No Fielder")

# checking the unique values in dismissal_kind and filling the null values with "Not Out"
print(df['dismissal_kind'].unique())
df['dismissal_kind']=df['dismissal_kind'].fillna("Not Out")

[nan 'SC Ganguly' 'RT Ponting' 'DJ Hussey' 'R Dravid' 'V Kohli'
 'JH Kallis' 'W Jaffer' 'MV Boucher' 'B Akhil' 'CL White' 'AA Noffke'
 'Z Khan' 'SB Joshi' 'PA Patel' 'ML Hayden' 'MS Dhoni' 'SK Raina'
 'JDP Oram' 'K Goel' 'JR Hopes' 'Yuvraj Singh' 'KC Sangakkara' 'T Kohli'
 'YK Pathan' 'SR Watson' 'DS Lehmann' 'M Kaif' 'M Rawat' 'RA Jadeja'
 'SK Warne' 'V Sehwag' 'L Ronchi' 'DJ Thornely' 'ST Jayasuriya' 'PR Shah'
 'RV Uthappa' 'AM Nayar' 'SM Pollock' 'S Chanderpaul' 'LRPL Taylor'
 'Y Venugopal Rao' 'VVS Laxman' 'AC Gilchrist' 'RG Sharma' 'SB Styris'
 'AS Yadav' 'A Symonds' 'WPUJC Vaas' 'SB Bangar' 'PP Ojha' 'BB McCullum'
 'WP Saha' 'Mohammad Hafeez' 'DPMD Jayawardene' 'IK Pathan' 'B Lee'
 'S Sohal' 'Kamran Akmal' 'Shahid Afridi' 'G Gambhir' 'MEK Hussey'
 'DJ Bravo' 'MA Khote' 'Harbhajan Singh' 'GC Smith' 'D Salunkhe'
 'RR Sarwan' 'PP Chawla' 'S Sreesanth' 'VRV Singh' 'SS Tiwary' 'P Kumar'
 'AB Agarkar' 'M Kartik' 'LR Shukla' 'AM Rahane' 'S Dhawan' 'Shoaib Malik'
 'KD Karthik' 'R Bhatia' 'MK Tiwary' 'MF Maharoof' 'SM Katich'
 'TM Srivastava' 'B Chipli' 'DW Steyn' 'DB Das' 'MK Pandey' 'HH Gibbs'
 'DNT Zoysa' 'D Kalyankrishna' 'SA Asnodkar' 'Salman Butt' 'BJ Hodge'
 'Umar Gul' 'AB Dinda' 'SP Fleming' 'S Vidyut' 'JA Morkel' 'LPC Silva'
 'DB Ravi Teja' 'RP Singh' 'Misbah-ul-Haq' 'SE Marsh' 'YV Takawale'
 'AB de Villiers' 'PJ Sangwan' 'Mohammad Asif' 'GD McGrath' 'S Badrinath'
 'Joginder Sharma' 'M Muralitharan' 'M Ntini' 'DT Patil' 'A Kumble'
 'S Anirudha' 'Sohail Tanvir' 'SK Trivedi' 'CK Kapugedera' 'A Chopra'
 'T Taibu' 'J Arunkumar' 'SP Goswami' 'R Vinay Kumar' 'A Mishra'
 'AD Mascarenhas' 'TM Dilshan' 'VY Mahesh' 'SR Tendulkar' 'Younis Khan'
 'NK Patel' 'I Sharma' 'Shoaib Akhtar' 'H Das' 'DR Smith' 'SD Chitnis'
 'A Nehra' 'VS Yeligati' 'MS Gony' 'L Balaji' 'LA Pomersbach' 'A Nel'
 'A Mukund' 'WA Mota' 'JP Duminy' 'A Flintoff' 'JD Ryder' 'KP Pietersen'
 'T Henderson' 'MM Patel' 'Kamran Khan' 'RS Bopara' 'CH Gayle'
 'MC Henriques' 'R Bishnoi' 'KV Sharma' 'PC Valthaty' 'RJ Quiney'
 'Yashpal Singh' 'Pankaj Singh' 'FH Edwards' 'AS Raut' 'AN Ghosh'
 'BAW Mendis' 'DL Vettori' 'RE van der Merwe' 'RR Powar' 'AA Bilakhia'
 'TL Suman' 'Shoaib Ahmed' 'GR Napier' 'MN van Wyk' 'NV Ojha'
 'LA Carseldine' 'M Vijay' 'SB Jakati' 'DA Warner' 'M Manhas' 'RJ Harris'
 'D du Preez' 'RR Raje' 'DS Kulkarni' 'M Morkel' 'AD Mathews' 'S Tyagi'
 'C Nanda' 'SL Malinga' 'J Botha' 'A Singh' 'GJ Bailey' 'AB McDonald'
 'Y Nagar' 'SS Shaikh' 'R Ashwin' 'T Thushara' 'Mohammad Ashraful'
 'CA Pujara' 'Anirudh Singh' 'AP Tare' 'AT Rayudu' 'R Sathish'
 'AA Jhunjhunwala' 'P Dogra' 'A Uniyal' 'MS Bisla' 'EJG Morgan' 'JM Kemp'
 'OA Shah' 'RS Gavaskar' 'SE Bond' 'KA Pollard' 'DP Nannes' 'MJ Lumb'
 'DR Martyn' 'S Narwal' 'AB Barath' 'FY Fazal' 'MD Mishra' 'S Ladda'
 'J Theron' 'SJ Srivastava' 'R Sharma' 'Mandeep Singh' 'AC Voges'
 'Jaskaran Singh' 'KAJ Roach' 'PD Collingwood' 'CK Langeveldt' 'VS Malik'
 'KM Jadhav' 'SW Tait' 'A Mithun' 'AP Dole' 'Harmeet Singh' 'R McLaren'
 'S Sriram' 'KP Appanna' 'C Madan' 'AG Paunikar' 'MR Marsh' 'AJ Finch'
 'STR Binny' 'B Sumanth' 'IR Jaggi' 'DT Christian' 'RV Gomez' 'MA Agarwal'
 'UBT Chand' 'UT Yadav' 'DJ Jacobs' 'Sunny Singh' 'AL Menaria'
 'AUK Pathan' 'WD Parnell' 'JJ van der Wath' 'R Ninan' 'MS Wade'
 'TD Paine' 'SB Wagh' 'JEC Franklin' 'Shakib Al Hasan' 'S Randiv'
 'BJ Haddin' 'NLTC Perera' 'JE Taylor' 'NL McCullum' 'RN ten Doeschate'
 'TR Birt' 'M Klinger' 'Harpreet Singh' 'Bipul Sharma' 'AC Blizzard'
 'CA Ingram' 'S Nadeem' 'DH Yagnik' 'KB Arun Karthik' 'AA Chavan'
 'ND Doshi' 'CJ Ferguson' 'Y Gnaneswara Rao' 'S Rana' 'BA Bhatt'
 'F du Plessis' 'DE Bollinger' 'RE Levi' 'MN Samuels' 'B Kumar'
 'SPD Smith' 'SA Yadav' 'HV Patel' 'GJ Maxwell' 'DJ Harris' 'Ankit Sharma'
 'SP Narine' 'JP Faulkner' 'KK Cooper' 'GB Hogg' 'RR Bhatkal' 'CJ McKay'
 'N Saini' 'DA Miller' 'P Negi' 'Azhar Mahmood' 'AC Thomas' 'RJ Peterson'
 'A Ashish Reddy' 'V Pratap Singh' 'MJ Clarke' 'Gurkeerat Singh'
 'VR Aaron' 'AP Majumdar' 'PA Reddy' 'AD Russell' 'CA Lynn' 'Sunny Gupta'
 'MC Juneja' 'KK Nair' 'GH Vihari' 'MDKJ Perera' 'B Laughlin'
 'Mohammed Shami' 'BMAJ Mendis' 'M Vohra' 'R Rampaul' 'P Awana'
 'SMSM Senanayake' 'BJ Rohrer' 'KL Rahul' 'J Syed Mohammad' 'Q de Kock'
 'BB Samantray' 'R Dhawan' 'MG Johnson' 'LJ Wright' 'AG Murtaza'
 'IC Pandey' 'X Thalaivan Sargunam' 'DJG Sammy' 'SV Samson'
 'KW Richardson' 'CH Morris' 'MM Sharma' 'CM Gautam' 'UA Birla'
 'Parvez Rasool' 'Sachin Baby' 'NM Coulter-Nile' 'CJ Anderson'
 'NJ Maddinson' 'AR Patel' 'JDS Neesham' 'TG Southee' 'PV Tambe'
 'MA Starc' 'BR Dunk' 'RR Rossouw' 'Shivam Sharma' 'LMP Simmons' 'VH Zol'
 'BCJ Cutting' 'Imran Tahir' 'R Shukla' 'BE Hendricks' 'M de Lange'
 'S Gopal' 'R Tewatia' 'JO Holder' 'JD Unadkat' 'SS Iyer' 'DJ Hooda'
 'SA Abbott' 'AN Ahmed' 'KS Williamson' 'Iqbal Abdulla' 'SN Khan'
 'D Wiese' 'HH Pandya' 'MJ McClenaghan' 'Anureet Singh' 'DJ Muthuswami'
 'PJ Cummins' 'Karanveer Singh' 'Sandeep Sharma' 'J Suchith' 'JC Buttler'
 'CR Brathwaite' 'MP Stoinis' 'Ishan Kishan' 'C Munro' 'AD Nath'
 'MJ Guptill' 'P Sahu' 'TM Head' 'M Ashwin' 'KH Pandya' 'NS Naik'
 'RR Pant' 'SW Billings' 'KC Cariappa' 'PSP Handscomb' 'Swapnil Singh'
 'J Yadav' 'UT Khawaja' 'HM Amla' 'JJ Bumrah' 'A Zampa' 'N Rana'
 'S Kaushik' 'F Behardien' 'KJ Abbott' 'ER Dwivedi' 'CJ Jordan'
 'S Aravind' 'TS Mills' 'YS Chahal' 'BA Stokes' 'JJ Roy' 'Vishnu Vinod'
 'CR Woakes' 'RA Tripathi' 'DL Chahar' 'V Shankar' 'Rashid Khan'
 'SN Thakur' 'C de Grandhomme' 'S Badree' 'AF Milne' 'Mohammad Nabi'
 'K Rabada' 'AJ Tye' 'Kuldeep Yadav' 'SP Jackson' 'Ankit Soni'
 'A Choudhary' 'AS Rajpoot' 'Washington Sundar' 'E Lewis' 'MA Wood'
 'RK Singh' 'DJM Short' 'K Gowtham' 'S Kaul' 'Mujeeb Ur Rahman'
 'Shubman Gill' 'Shivam Mavi' 'TK Curran' 'TA Boult' 'H Klaasen' 'RK Bhui'
 'JC Archer' 'PP Shaw' 'LE Plunkett' 'Basil Thampi' 'M Markande'
 'Mustafizur Rahman' 'BB Sran' 'AD Hales' 'MK Lomror' 'Mohammed Siraj'
 'DR Shorey' 'MM Ali' 'P Chopra' 'IS Sodhi' 'Abhishek Sharma'
 'JPR Scantlebury-Searles' 'SO Hetmyer' 'S Dube' 'Navdeep Saini'
 'JM Bairstow' 'KMA Paul' 'N Pooran' 'P Ray Barman' 'SM Curran'
 'GC Viljoen' 'S Lamichhane' 'RD Chahar' 'M Prasidh Krishna' 'SD Lad'
 'R Parag' 'JL Denly' 'LS Livingstone' 'KK Ahmed' 'AJ Turner'
 'SE Rutherford' 'MJ Santner' 'P Simran Singh' 'JL Pattinson' 'T Banton'
 'D Padikkal' 'YBK Jaiswal' 'RD Gaikwad' 'TU Deshpande' 'Abdul Samad'
 'PK Garg' 'JR Philippe' 'KL Nagarkoti' 'CV Varun' 'I Udana'
 'Ravi Bishnoi' 'AT Carey' 'N Jagadeesan' 'A Nortje' 'Kartik Tyagi'
 'SS Cottrell' 'Arshdeep Singh' 'DR Sams' 'M Jansen' 'RM Patidar'
 'Shahbaz Ahmed' 'KA Jamieson' 'JA Richardson' 'Lalit Yadav'
 'M Shahrukh Khan' 'Virat Singh' 'FA Allen' 'C Sakariya' 'DJ Malan'
 'KS Bharat' 'PWH de Silva' 'GHS Garton' 'AK Markram' 'Avesh Khan'
 'VR Iyer' 'GD Phillips' 'TL Seifert' 'Anmolpreet Singh' 'Anuj Rawat'
 'NT Ellis' 'RV Patel' 'TH David' 'DP Conway' 'Tilak Varma' 'R Powell'
 'PBB Rajapaksa' 'RA Bawa' 'A Badoni' 'R Shepherd' 'DJ Willey'
 'D Pretorius' 'Harpreet Brar' 'A Manohar' 'JM Sharma' 'OF Smith'
 'D Brevis' 'VG Arora' 'B Sai Sudharsan' 'Ramandeep Singh' 'Rasikh Salam'
 'HE van der Dussen' 'PVD Chameera' 'SS Prabhudessai' 'Akash Deep'
 'Aman Hakim Khan' 'AS Joseph' 'HR Shokeen' 'LH Ferguson' 'Yash Dayal'
 'DJ Mitchell' 'B Indrajith' 'Shashank Singh' 'AS Roy' 'Harshit Rana'
 'Umran Malik' 'K Kartikeya' 'KS Sharma' 'Mohsin Khan' 'Simarjeet Singh'
 'M Theekshana' 'Mukesh Choudhary' 'T Stubbs' 'R Sanjay Yadav' 'A Tomar'
 'OC McCoy' 'Sikandar Raza' 'Rahmanullah Gurbaz' 'KR Mayers' 'HC Brook'
 'AU Rashid' 'C Green' 'N Wadhera' 'Abishek Porel' 'MG Bracewell'
 'Arshad Khan' 'MW Short' 'YV Dhull' 'Dhruv Jurel' 'Yudhvir Singh'
 'Atharva Taide' 'Liton Das' 'PD Salt' 'Vijaykumar Vyshak'
 'Arjun Tendulkar' 'Naveen-ul-Haq' 'Noor Ahmad' 'P Dubey' 'JE Root'
 'KM Asif' 'Sanvir Singh' 'PN Mankad' 'Vivrant Sharma' 'MD Shanaka'
 'DG Nalkande' 'R Ravindra' 'SD Hope' 'Sumit Kumar' 'Azmatullah Omarzai'
 'Naman Dhir' 'G Coetzee' 'Sameer Rizvi' 'Mayank Dagar' 'A Raghuvanshi'
 'Ashutosh Sharma' 'Saurav Chauhan' 'Kumar Kushagra' 'BR Sharath'
 'Nithish Kumar Reddy' 'WG Jacks' 'J Fraser-McGurk' 'Tanush Kotian'
 'KA Maharaj' 'Arshad Khan (2)' 'R Sai Kishore' 'AA Kulkarni' 'MJ Suthar'
 'Gulbadin Naib' 'SB Dubey' 'D Ferreira' 'Mukesh Kumar' 'T Kohler-Cadmore']
[nan 'caught' 'bowled' 'run out' 'lbw' 'retired hurt' 'stumped'
 'caught and bowled' 'hit wicket' 'obstructing the field' 'retired out']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       260920 non-null  object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  260920 non-null  object
 15  dismissal_kind    260920 non-null  object
 16  fielder           260920 non-null  object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [8]:
# Replace team names and city names for consistency
df['batting_team'] = df['batting_team'].replace('Delhi Daredevils', 'Delhi Capitals')
df['bowling_team'] = df['bowling_team'].replace('Delhi Daredevils', 'Delhi Capitals')
df['batting_team'] = df['batting_team'].replace('Deccan Chargers', 'Sunrisers Hyderabad')
df['bowling_team'] = df['bowling_team'].replace('Deccan Chargers', 'Sunrisers Hyderabad')
df['batting_team'] = df['batting_team'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant')
df['bowling_team'] = df['bowling_team'].replace('Rising Pune Supergiants', 'Rising Pune Supergiant')
df['batting_team'] = df['batting_team'].replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
df['bowling_team'] = df['bowling_team'].replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru')
df['batting_team'] = df['batting_team'].replace('Kings XI Punjab', 'Punjab Kings')
df['bowling_team'] = df['bowling_team'].replace('Kings XI Punjab', 'Punjab Kings')

In [9]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,Not Dismissed,Not Out,No Fielder
1,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,Normal,0,Not Dismissed,Not Out,No Fielder
2,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,Not Dismissed,Not Out,No Fielder
3,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,Normal,0,Not Dismissed,Not Out,No Fielder
4,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,Normal,0,Not Dismissed,Not Out,No Fielder

In [10]:
df.to_csv("cleaned_deliveries.csv", index=False)